version: '3.1'
services:
  web:
    image: dhanrajnath/fel3
    ports:
      - 3000:3000
    depends_on:
      - postgresql
      - svc

  svc:
    image: dhanrajnath/bel
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jobs
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
  postgresql:
    image: dhanrajnath/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jobs
