apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bc15
  namespace: bc15
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
