apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bc15
  namespace: bc15
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
